[project]
name = "spot-gazer-backend"
version = "0.1.0"
description = "Backend service for the parking lot occupancy recognition system"
authors = [{ name = "AKrekhovetskyi", email = "akrechovetskiy@gmail.com" }]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "django>=5.2.4",
    "django-debug-toolbar>=5.2.0",
    "folium>=0.20.0",
    "djangorestframework>=3.16.0",
    "markdown>=3.8.2",
    "django-filter>=25.1",
    "mysqlclient>=2.2.7",
    "djangorestframework-simplejwt>=5.5.0",
    "drf-spectacular>=0.28.0",
    "django-celery-beat>=2.8.1",
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.2.0"
django-stubs = ">=5.2.0"

[tool.poetry.group.test.dependencies]
faker = "^37.4.0"
parameterized = "^0.9.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
venvPath = "."
venv = ".venv"
exclude = ["**/migrations/**"]
