# Generated by Django 5.2.4 on 2025-07-12 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livemap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='livemap.city'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='livemap.country'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_lots', related_query_name='parking_lot', to='livemap.address'),
        ),
        migrations.AlterField(
            model_name='videostreamsource',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_sources', related_query_name='stream_source', to='livemap.parkinglot'),
        ),
        migrations.AlterField(
            model_name='videostreamsource',
            name='processing_rate',
            field=models.PositiveIntegerField(help_text='In seconds. The same for all video streams from the same parking lot.'),
        ),
    ]
