# Generated by Django 5.2.4 on 2025-07-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livemap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostreamsource',
            name='in_use_until',
            field=models.DateTimeField(blank=True, help_text='Date and time in UTC timezone until the video stream is in use.', null=True),
        ),
    ]
