# Generated by Django 5.2.4 on 2025-07-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livemap', '0002_alter_address_city_alter_city_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='occupancy',
            options={'get_latest_by': 'timestamp', 'verbose_name_plural': 'occupancy'},
        ),
        migrations.AlterField(
            model_name='videostreamsource',
            name='processing_rate',
            field=models.PositiveIntegerField(choices=[(5, '5 seconds'), (10, '10 seconds'), (30, '30 seconds'), (60, '60 seconds'), (120, '120 seconds'), (180, '180 seconds')], help_text='In seconds. The same for all video streams from the same parking lot.'),
        ),
    ]
