# Generated by Django 5.2.4 on 2025-07-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livemap', '0002_videostreamsource_in_use_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videostreamsource',
            name='parking_zone',
        ),
    ]
