# Generated by Django 5.2.4 on 2025-07-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livemap', '0003_remove_videostreamsource_parking_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videostreamsource',
            name='in_use_until',
            field=models.DateTimeField(blank=True, help_text='Date and time in UTC timezone and ISO-8601 format until the video stream is in use.', null=True),
        ),
    ]
