# Generated by Django 5.2.4 on 2025-08-01 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livemap', '0004_alter_videostreamsource_in_use_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyOccupancySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_occupied_spots', models.PositiveSmallIntegerField()),
                ('hour', models.PositiveSmallIntegerField(help_text='0-23')),
                ('date', models.DateField()),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_occupancy', to='livemap.parkinglot')),
            ],
            options={
                'unique_together': {('parking_lot', 'hour', 'date')},
            },
        ),
    ]
